### ISSUE TITLE
[BUG] Queued Videos Remain in Loading State (Temporary File Issue?)

### ISSUE THREAD

**Issue by engels74** [arabcoders/ytptube#173]
**[BUG] Queued Videos Remain in Loading State (Temporary File Issue?)**

### **Description**
After setting up `ytptube` with the provided configuration, videos are downloaded successfully, but the queued videos remain in a loading state indefinitely. The issue persists even though the downloaded files are accessible and complete.

---

#### `compose.yaml`
```yaml
services:
  ytptube:
    container_name: ytptube
    hostname: ytptube.internal
    image: ghcr.io/arabcoders/ytptube
    user: 1000:1000
    labels:
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.discord.webhook=https://discord.com/api/webhooks/xxxxxxxx/xxxxxxxxxx"
      - "org.hotio.pullio.author.avatar=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/youtube.webp"
    volumes:
      - /opt/docker-all/miscSoftware/ytptube/config:/config:rw  # Configuration files
      - /opt/docker-all/miscSoftware/ytptube/downloads:/downloads:rw  # Downloaded files
    tmpfs:
      - /tmp
    environment:
      - TZ=Europe/Copenhagen
      - YTP_CONFIG_PATH=/config
      - YTP_DOWNLOAD_PATH=/downloads
      - YTP_TEMP_PATH=/tmp
      - YTP_TEMP_KEEP=false  # Delete temporary files after download
      - YTP_KEEP_ARCHIVE=false  # Disable download history to save space
      - YTP_REMOVE_FILES=true  # Delete files when removed from the UI
      - YTP_MAX_WORKERS=2  # Limit concurrent downloads
      - YTP_LOG_LEVEL=info  # Reduce logging verbosity
      - YTP_ACCESS_LOG=false  # Disable access logs
      - YTP_DEBUG=false  # Disable debug mode
      - YTP_UI_UPDATE_TITLE=true  # Keep UI updated
      - YTP_ALLOW_MANIFESTLESS=true  # Allow downloading live streams
      - YTP_BASIC_MODE=true
    networks:
      - caddy_backbone
    restart: always

networks:
  caddy_backbone:
    external: true
```

#### File Permissions
The download folder is owned by the `xvps` user (UID 1000), which has the correct group permissions:
```bash
xvps@l7ext2:~$ id
uid=1000(xvps) gid=1000(xvps) groups=1000(xvps),27(sudo),100(users),988(docker)

xvps@l7ext2:~$ ls -alh /opt/docker-all/miscSoftware/
total 16K
drwxr-xr-x 4 xvps xvps 4.0K Jan 15 22:27 .
drwxr-xr-x 3 xvps xvps 4.0K Jan 15 22:10 ..
drwxrwxr-x 4 xvps xvps 4.0K Jan 16 12:29 caddy
drwxr-xr-x 4 xvps xvps 4.0K Jan 17 21:30 ytptube

xvps@l7ext2:~$ ls -alh /opt/docker-all/miscSoftware/ytptube/
total 16K
drwxr-xr-x 4 xvps xvps 4.0K Jan 17 21:30 .
drwxr-xr-x 4 xvps xvps 4.0K Jan 15 22:27 ..
drwxr-xr-x 2 xvps xvps 4.0K Jan 17 21:21 config
drwxr-xr-x 2 xvps xvps 4.0K Jan 17 21:21 downloads
```

#### `ytdlp.json`
```json
{
  "format": "bv*[height<=1080]+ba/b[height<=1080]",
  "merge_output_format": "mkv",
  "outtmpl": "%(title)s.%(ext)s",
  "restrictfilenames": true,
  "nooverwrites": true,
  "noplaylist": true,
  "verbose": true
}
```

---

### **Steps to Reproduce**
1. Set up `ytptube` using the provided `compose.yaml` and `ytdlp.json` configurations.
2. Queue a video for download (e.g., `https://www.youtube.com/watch?v=wF4R597ANIE`).
3. Observe that the video remains in a loading state in the queue, even though the file is fully downloaded and accessible.

---

### **Expected Behavior**
The queued video should complete its loading state and disappear from the queue once the download is finished.

---

### **Actual Behavior**
The queued video remains in a loading state indefinitely, despite the file being successfully downloaded.

---

### **Logs**
Logs can be found here:  
[Log File](https://logs.notifiarr.com/?4983ca641e4a947b#E5QwokCZoyFUcv9SwhootiNDqpH9ZihFkj6HCNUfZ2X9)

---

### **Screenshots**
https://i.postimg.cc/RVyM3gYp/SCR-20250117-lkox-2.png

**Comment by arabcoders** [comment]
Hi, Thanks for the report the relevant part of log is

```
2025-01-17T20:21:50.857685941Z 21:21:50 [asyncio] [ERROR] Task exception was never retrieved
2025-01-17T20:21:50.857731961Z future: <Task finished name='update-8980f7b7-5222-417e-bf61-165c8472f0fd' coro=<Download.progress_update() done, defined at /app/app/library/Download.py:310> exception=FileNotFoundError(2, 'No such file or directory')>
2025-01-17T20:21:50.857742866Z Traceback (most recent call last):
2025-01-17T20:21:50.857748990Z   File "/usr/local/lib/python3.11/multiprocessing/managers.py", line 814, in _callmethod
2025-01-17T20:21:50.857755645Z     conn = self._tls.connection
2025-01-17T20:21:50.857761381Z            ^^^^^^^^^^^^^^^^^^^^
2025-01-17T20:21:50.857767358Z AttributeError: 'ForkAwareLocal' object has no attribute 'connection'
2025-01-17T20:21:50.857774089Z 
2025-01-17T20:21:50.857779375Z During handling of the above exception, another exception occurred:
2025-01-17T20:21:50.857785756Z 
2025-01-17T20:21:50.857789767Z Traceback (most recent call last):
2025-01-17T20:21:50.857812684Z   File "/app/app/library/Download.py", line 321, in progress_update
2025-01-17T20:21:50.857817192Z     status = await self.update_task
2025-01-17T20:21:50.857820830Z              ^^^^^^^^^^^^^^^^^^^^^^
2025-01-17T20:21:50.857824586Z   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
2025-01-17T20:21:50.857830000Z     result = self.fn(*self.args, **self.kwargs)
2025-01-17T20:21:50.857836100Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-17T20:21:50.857842048Z   File "<string>", line 2, in get
2025-01-17T20:21:50.857848621Z   File "/usr/local/lib/python3.11/multiprocessing/managers.py", line 818, in _callmethod
2025-01-17T20:21:50.857855341Z     self._connect()
2025-01-17T20:21:50.857861124Z   File "/usr/local/lib/python3.11/multiprocessing/managers.py", line 805, in _connect
2025-01-17T20:21:50.857867889Z     conn = self._Client(self._token.address, authkey=self._authkey)
2025-01-17T20:21:50.857874260Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-17T20:21:50.857879847Z   File "/usr/local/lib/python3.11/multiprocessing/connection.py", line 519, in Client
2025-01-17T20:21:50.857883785Z     c = SocketClient(address)
2025-01-17T20:21:50.857887356Z         ^^^^^^^^^^^^^^^^^^^^^
2025-01-17T20:21:50.857891134Z   File "/usr/local/lib/python3.11/multiprocessing/connection.py", line 647, in SocketClient
2025-01-17T20:21:50.857895081Z     s.connect(address)
2025-01-17T20:21:50.857898801Z FileNotFoundError: [Errno 2] No such file or directory
```
Sadly it doesn't exactly list where the exception was thrown, anyhow i wrapped them into try caught this should fix it, it's weird as the processing is done it seems but somehow ytptube is unable to access the file. thus triggering the `FileNotFoundError` exception.

I have pushed potential fix in dev branch please do try it and report back.

**Comment by engels74** [comment]
Thanks for the quick reply.

1) Pulled the latest from `:dev` branch
2) Used exact same settings and same video as mentioned in original issue

Full logs:
https://logs.notifiarr.com/?bf463db8a7bf7ddd#3rt2Bg7bGhqSSTurmL1DGzaGgQFcSCmTfaq33goyaHhk

**Comment by arabcoders** [comment]
> Thanks for the quick reply.
> 
> 1. Pulled the latest from `:dev` branch
> 2. Used exact same settings and same video as mentioned in original issue
> 
> Full logs: https://logs.notifiarr.com/?bf463db8a7bf7ddd#3rt2Bg7bGhqSSTurmL1DGzaGgQFcSCmTfaq33goyaHhk
> 
> **Edit:** Really odd. If I set `YTP_DEBUG` to `true`, it works fine?
> 
> Full logs (with `YTP_DEBUG` set to `true`): https://logs.notifiarr.com/?269f0758ac8e8780#CuWqdXE6DR8m5EosuRDkvtR6tYGC3mjwWHHiBDfxwC2y

can you try using one worker instead of 2 and if it get stuck if you click the reload button does it go away?

**Comment by engels74** [comment]
> > Thanks for the quick reply.
> > 
> > 1. Pulled the latest from `:dev` branch
> > 2. Used exact same settings and same video as mentioned in original issue
> > 
> > Full logs: https://logs.notifiarr.com/?bf463db8a7bf7ddd#3rt2Bg7bGhqSSTurmL1DGzaGgQFcSCmTfaq33goyaHhk
> > **Edit:** Really odd. If I set `YTP_DEBUG` to `true`, it works fine?
> > Full logs (with `YTP_DEBUG` set to `true`): https://logs.notifiarr.com/?269f0758ac8e8780#CuWqdXE6DR8m5EosuRDkvtR6tYGC3mjwWHHiBDfxwC2y
> 
> can you try using one worker instead of 2 and if it get stuck if you click the reload button does it go away?

`YTP_MAX_WORKERS` set to `1` (and the `YTP_DEBUG` set to `false`) - error still happening - here are the full logs:
https://logs.notifiarr.com/?d5787ed881ad1d45#5QbQgSWDhgUfc5VGf61HGEPbbYd9qAV6xBSYQiXe8vYn

But yes, it disappears after reloading

**Comment by arabcoders** [comment]
> > > Thanks for the quick reply.
> > > 
> > > 1. Pulled the latest from `:dev` branch
> > > 2. Used exact same settings and same video as mentioned in original issue
> > > 
> > > Full logs: https://logs.notifiarr.com/?bf463db8a7bf7ddd#3rt2Bg7bGhqSSTurmL1DGzaGgQFcSCmTfaq33goyaHhk
> > > **Edit:** Really odd. If I set `YTP_DEBUG` to `true`, it works fine?
> > > Full logs (with `YTP_DEBUG` set to `true`): https://logs.notifiarr.com/?269f0758ac8e8780#CuWqdXE6DR8m5EosuRDkvtR6tYGC3mjwWHHiBDfxwC2y
> > 
> > 
> > can you try using one worker instead of 2 and if it get stuck if you click the reload button does it go away?
> 
> `YTP_MAX_WORKERS` set to `1` (and the `YTP_DEBUG` set to `false`) - error still happening - here are the full logs: https://logs.notifiarr.com/?d5787ed881ad1d45#5QbQgSWDhgUfc5VGf61HGEPbbYd9qAV6xBSYQiXe8vYn
> 
> But yes, it disappears after reloading

Alright thanks, i'll have to dig deeper to understand the issue more, the exception is being thrown somewhere else not where the stack is showing for some reason, i should have something tomorrow.

**Comment by engels74** [comment]
Thanks to you too. And no problem!

Just to show you, this is how it looks with:

1) `YTP_DEBUG` set to `true`:
[GIF w/ console shown](https://up.shx.gg/6XjpvJvYC.gif) (+ [logs](https://logs.notifiarr.com/?23c48450100e9e12#vzmtThDUT5q6dcnn61Yf6W1g1afx44QtasBRNbi5oof))


2) `YTP_DEBUG` set to `false`:
[GIF w/ console shown](https://up.shx.gg/6XjqpYWEd.gif) (+ [logs](https://logs.notifiarr.com/?8eaf5b053248d1f4#DqMaAZ6yBX2VjaKg18VJycwhdoXyjBXE3ei7dgL3XdtQ))

**Comment by arabcoders** [comment]
@engels74 I have pushed a fix to both dev and latest, please try now

**Comment by engels74** [comment]
> [@engels74](https://github.com/engels74) I have pushed a fix to both dev and latest, please try now

New error I guess, it spams up the log with this:
https://logs.notifiarr.com/?6e8ea3d27f36e61f#D9X5t9hygMhjRzqsGaY8hzM7BUVjxfwdNNXwN126nnUy

**Comment by arabcoders** [comment]
> > [@engels74](https://github.com/engels74) I have pushed a fix to both dev and latest, please try now
> 
> Pulled the latest image from `:dev`
> 
> Current docker compose - unchanged, but just for reference (compose.yaml): https://logs.notifiarr.com/?c1c9c71bdfcd5249#BE5JAfR8bJ6sLjhHFmVqrQvBc6SquiYHYfsj8UGrg7RU
> 
> Current ytdlp.json - unchanged, but just for reference: https://logs.notifiarr.com/?8103e9741a4f5a49#9vNfgjbSEF68oEkKsMpsmrn3dM61YemNk84tHkg1N5m1
> 
> New error I guess, it spams up the log with this: https://logs.notifiarr.com/?6e8ea3d27f36e61f#D9X5t9hygMhjRzqsGaY8hzM7BUVjxfwdNNXwN126nnUy

something is really weird in your environment causing this i tried on 4 different servers and locally none showing this error, lol

Last attempt, i pushed another fix to dev right now, it should still show you an error however it will continue to trigger the completed event to move the item from queue to completed section.

Please try it.

**Comment by engels74** [comment]
Just gives this:
https://logs.notifiarr.com/?f13c50ba8489cc22#EuHoXrwMsvksZWAN8MkoBue7Bf7pdDqqpQQBAJu9BAkN

Issue still persists, still just spinning/loading 😭

No idea mate, it's a quite basic Ubuntu 24.04.1 LTS:
```
xvps@l7ext2:~/stacks/001-ytptube$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble
```

Docker version:
```
Docker version 27.5.0, build a187fa5
```

I'm ussing Caddy, the Caddyfile looks like this:
https://logs.notifiarr.com/?00535cca3cdf82f8#GGi5yYKrzYk9YwqxRLfhVww9HzpDbyM5qXG8dKNSesK5

Caddy compose YAML is quite basic as well:
https://logs.notifiarr.com/?285d34f3bb5dadbf#DX4A8eL7bcvKiqBJANyWeNCZgjXucKk49BJUvnEVxQWL

 
The most odd thing is that enabling the `YTP_DEBUG` (set to `1`) fixes the issue, I have no idea what's going on lol.

**Comment by arabcoders** [comment]
`YTP_DEBUG` enables the debug server, which slow down the code execution, probably giving enough time for the post processing to complete. this is the most logical explanation i can think of, Please do try the last fix i pushed, if it works ok I'll just hide the error and move on xD

**Comment by engels74** [comment]
The [above comment](https://github.com/arabcoders/ytptube/issues/173#issuecomment-2599762814) was using this: https://github.com/users/arabcoders/packages/container/ytptube/339179346?tag=dev-20250118-3f2b9fe

I can't see other commits? 😄

**Comment by arabcoders** [comment]
Hmm, could you hop on the discord channel? the link is in README
